name: sejmouvisds
channels:
  - conda-forge
dependencies:
  - python=3.10
  - tqdm
  - requests
  - pandas
  - ipykernel
  - matplotlib
  - seaborn
  - python-dotenv
  - spotipy
  - selenium
  - pandarallel
  - musicbrainzngs
  - gdown
  - plotly
  - scikit-learn
  # skops.io is a library for persisting trained sklearn models
  - skops
  # imblearn is a library for dealing with imbalanced datasets in sklearn
  - imbalanced-learn
  - pip:
      - lyricsgenius
