name: sejmouvisds
channels:
  - conda-forge
dependencies:
  - python=3.10
  - tqdm
  - requests
  - pandas
  - ipykernel
  - matplotlib
  - seaborn
  - python-dotenv
  - spotipy
  - selenium
  - pandarallel
  - pip:
      - lyricsgenius
